name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun i
      - run: bun run dist
      - run: npm publish
        working-directory: dist
